#!/usr/bin/env python3
import os
from typing import Optional

TICI = os.path.isfile('/TICI')
RESERVED_PORT = 8022  # sshd
STARTING_PORT = 8001


def new_port(port: int):
  port += STARTING_PORT
  return port + 1 if port >= RESERVED_PORT else port


class Service:
  def __init__(self, port: int, should_log: bool, frequency: float, decimation: Optional[int] = None):
    self.port = port
    self.should_log = should_log
    self.frequency = frequency
    self.decimation = decimation

DCAM_FREQ = 10. if not TICI else 20.

# should_log picks what lands in rlog. Only two questions are asked of these
# logs, so only what answers them is recorded:
#
#   steering quality -- carState (measured angle, torque, EPS torque, faults),
#   carControl (the steer request and the applied actuatorsOutput), and
#   controlsState (the lateral controller's error/output/saturated, curvature,
#   and the latAccelFactor/friction actually in force). carEvents says which
#   events fired, carParams the static tuning they ran against, and
#   liveParameters the angle offset, roll and stiffness the curvature maths
#   needs.
#
#   curve fallback -- modelV2 is the profile source and lateralPlan is what
#   cal_curve_speed falls back to when the model profile is invalid, so both
#   are needed to say which one was driving and why.
#
# errorLogMessage stays because it costs nothing until something breaks.
#
# Everything else is off. That includes `can` and `sendcan`, which were the two
# largest by a wide margin and whose content reaches carState/carControl
# decoded anyway -- note this is what makes these logs unusable for
# process_replay of controlsd, which feeds on `can`.

services = {
  # service: (should_log, frequency, qlog decimation (optional))
  # note: the "EncodeIdx" packets will still be in the log
  "sensorEvents": (False, 100., 100),
  "gpsNMEA": (False, 9.),
  "deviceState": (False, 2., 1),
  "can": (False, 100.),
  "controlsState": (True, 100., 10),
  "pandaStates": (False, 2., 1),
  "peripheralState": (False, 2., 1),
  "radarState": (False, 20., 5),
  "roadEncodeIdx": (False, 20., 1),
  "liveTracks": (False, 20.),
  "sendcan": (False, 100., 139),
  "logMessage": (False, 0.),
  "errorLogMessage": (True, 0., 1),
  "liveCalibration": (False, 4., 4),
  "androidLog": (False, 0.),
  "carState": (True, 100., 10),
  "carControl": (True, 100., 10),
  "longitudinalPlan": (False, 20., 5),
  "procLog": (False, 0.5),
  "gpsLocationExternal": (False, 10., 10),
  "ubloxGnss": (False, 10.),
  "qcomGnss": (False, 2.),
  "clocks": (False, 1., 1),
  "ubloxRaw": (False, 20.),
  "liveLocationKalman": (False, 20., 5),
  "liveParameters": (True, 20., 5),
  "cameraOdometry": (False, 20., 5),
  "lateralPlan": (True, 20., 5),
  "thumbnail": (False, 0.2, 1),
  "carEvents": (True, 1., 1),
  "carParams": (True, 0.02, 1),
  "roadCameraState": (False, 20., 20),
  "driverCameraState": (False, DCAM_FREQ, DCAM_FREQ),
  "driverEncodeIdx": (False, DCAM_FREQ, 1),
  "driverState": (False, DCAM_FREQ, DCAM_FREQ / 2),
  "driverMonitoringState": (False, DCAM_FREQ, DCAM_FREQ / 2),
  "wideRoadEncodeIdx": (False, 20., 1),
  "wideRoadCameraState": (False, 20., 20),
  "modelV2": (True, 20., 40),
  "managerState": (False, 2., 1),
  "uploaderState": (False, 0., 1),
  "navInstruction": (False, 0., 10),
  "navRoute": (False, 0.),
  "navThumbnail": (False, 0.),
  "roadLimitSpeed": (False, 0.),
  "liveTorqueParameters": (False, 4., 1),
  # shane
  "dynamicFollowData": (False, 20.),

  # debug
  "testJoystick": (False, 0.),
  "roadEncodeData": (False, 20.),
  "driverEncodeData": (False, DCAM_FREQ),
  "wideRoadEncodeData": (False, 20.),
}
service_list = {name: Service(new_port(idx), *vals) for  # type: ignore
                idx, (name, vals) in enumerate(services.items())}


def build_header():
  h = ""
  h += "/* THIS IS AN AUTOGENERATED FILE, PLEASE EDIT services.py */\n"
  h += "#ifndef __SERVICES_H\n"
  h += "#define __SERVICES_H\n"
  h += "struct service { char name[0x100]; int port; bool should_log; int frequency; int decimation; };\n"
  h += "static struct service services[] = {\n"
  for k, v in service_list.items():
    should_log = "true" if v.should_log else "false"
    decimation = -1 if v.decimation is None else v.decimation
    h += '  { "%s", %d, %s, %d, %d },\n' % \
         (k, v.port, should_log, v.frequency, decimation)
  h += "};\n"
  h += "#endif\n"
  return h


if __name__ == "__main__":
  print(build_header())
